<?php
$GLOBALS['language']['zh_cn'] = array
(
	'LOGIN' => '登录',
	'SIGNUP' => '注册',
	'NEW_ACCOUNT_SIGNUP' => '新用户注册',
	'LOGOUT' => '退出',
	'PROFILE' => '个人设置',
	'CHANGE_PASSWORD' => '修改密码',
	'NEED_SIGNUP' => '还没有投食帐号？<a href="?c=user&a=signup">立即注册</a>',
	'SUBMIT' => '确定',

	'INDEX_PAGE' => '首页',
	'BLOG' => '干粮',
	'ADD_FEED' => '添加Feed',
	'NAME' => '标题',
	'FILE' => '文件位置',
	'DES' => '描述',
	'RECIPE' => '抓取模板',
	'CRONTAB' => '定时',
	'FAVICON' => '网站图标',
	'SITE_URL' => '网站地址',
	'TYPE' => '类型',
	'ADD' => '添加',
	'ALL_SUBSCRIBED' => '所有订阅',
	'MY_SUBSCRIBED' => '我的订阅',
	'DELIVER_PER_DAY' => '每日投递',
	'DELIVER_PER_WEEK' => '每周投递',
	'DELIVER_PER_MONTH' => '每月投递',
	'DELIVER' => '推送',
	'DELIVERED' => '已推送',
	'SUBSCRIBE' => '订阅',
	'UNSUBSCRIBE' => '取消订阅',
	'ABOUT_TOUSHI' => '关于投食',
	'TOUSHI' => '投食',
	'OLDER' => '&larr; 前页',
	'NEWER' => '后页 &rarr;',

	'NICKNAME' => '昵称',
	'PASSWORD' => '密码',
	'EMAIL' => '邮箱',
	'SUBSCRIBED_ACCOUNT' => '订阅帐号',
	'TIMEZONE' => '时区',
	'OLD_PASSWORD' => '旧密码',
	'NEW_PASSWORD' => '新密码',
	'PROTOCAL' => '投食用户协议',
	'AGREE_PROTOCAL' => '<small class="muted">我已阅读并接收<a href="#protocal" data-toggle="modal">《投食用户协议》</a></small>',
	'NOT_AGREE_PROTOCAL' => '您还未接受投食用户协议',
	'PROTOCAL_TEXT' => '<ol><li>订阅服务免费提供</li><li>其他待补充</li></ol>',

	'EMAIL_INVALID' => '邮箱格式不正确',
	'EMAIL_TOO_LONG' => '邮箱过长，请重新输入',
	'EMAIL_EMPTY' => '请填写邮箱',
	'EMAIL_IS_EXISTED' => '邮箱已存在，请重新输入',
	'NICKNAME_EMPTY' => '请填写昵称',
	'NICKNAME_TOO_SHORT' => '昵称过短，请重新输入',
	'NICKNAME_TOO_LONG' => '昵称过长，请重新输入',
	'NICKNAME_IS_EXISTED' => '昵称已存在，请重新输入',
	'PASSWORD_EMPTY' => '请填写密码',
	'PASSWORD_TOO_SHORT' => '密码过短，请重新输入',
	'PASSWORD_TOO_LONG' => '密码过长，请重新输入',
	'SUBSCRIBED_ACCOUNT_INVALID' => '订阅帐号格式不正确',
	'SUBSCRIBED_ACCOUNT_TOO_LONG' => '订阅帐号过长，请重新输入',
	'SUBSCRIBED_ACCOUNT_EMPTY' => '请填写订阅帐号',
	'SUBSCRIBED_ACCOUNT_IS_EXISTED' => '订阅帐号已存在，请重新输入',
	'SIGNED_UP' => '注册用户成功！',
	'SIGNED_UP_TEXT' => '欢迎 <strong>%s</strong> 加入投食，点击跳转至 <a href="?c=user&amp;a=login">登录页</a>',
	'UPDATE_PROFILE_TEXT' => '<strong>%s</strong> 修改个人设置成功，点击跳转至 <a href="' . c('site_domain') . '">首页</a>',
	'NOT_VERIFIED' => '邮箱或密码不正确，请重新输入',
	'OLD_PASSWORD_NOT_VERIFIED' => '旧密码不正确，请重新输入',
	'CHANGE_PASSWORD_TEXT' => '<strong>%s</strong> 修改密码成功，请重新<a href="?c=user&a=login">登录</a>',
);